services:
  webserver:
    build: .
    image: html-container  # Name of your image
    ports:
      - "8090:80"  # Map port 80 in the container to port 8090 on the host
    volumes:
      - ./cloud:/usr/share/nginx/html  # Bind mount the cloud directory
    container_name: html-container
